/*
   Copyright 2015-2018 Marco De Salvo

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

using System;
using System.Collections.Generic;
using System.Linq;

namespace RDFSharp.Semantics
{

    /// <summary>
    /// RDFOntologyReasonerExtensions contains utility methods for miscellaneous reasoning tasks
    /// </summary>
    public static class RDFOntologyReasonerExtensions {

        #region ClearInferences
        /// <summary>
        /// Clears all the taxonomy entries marked as semantic inferences generated by a reasoner
        /// </summary>
        public static void ClearInferences(this RDFOntology ontology) {
            if (ontology != null) {
                ontology.Model.ClearInferences();
                ontology.Data.ClearInferences();
            }           
        }

        /// <summary>
        /// Clears all the taxonomy entries marked as semantic inferences generated by a reasoner
        /// </summary>
        public static void ClearInferences(this RDFOntologyModel ontologyModel) {
            if (ontologyModel != null) {
                ontologyModel.ClassModel.ClearInferences();
                ontologyModel.PropertyModel.ClearInferences();
            }           
        }

        /// <summary>
        /// Clears all the taxonomy entries marked as semantic inferences generated by a reasoner
        /// </summary>
        public static void ClearInferences(this RDFOntologyClassModel ontologyClassModel) {
            if (ontologyClassModel != null) {
                var cacheRemove = new Dictionary<Int64, Object>();

                //SubClassOf
                foreach (var t in ontologyClassModel.Relations.SubClassOf.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyClassModel.Relations.SubClassOf.Entries.Remove(c); }
                cacheRemove.Clear();

                //EquivalentClass
                foreach (var t in ontologyClassModel.Relations.EquivalentClass.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyClassModel.Relations.EquivalentClass.Entries.Remove(c); }
                cacheRemove.Clear();

                //DisjointWith
                foreach (var t in ontologyClassModel.Relations.DisjointWith.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyClassModel.Relations.DisjointWith.Entries.Remove(c); }
                cacheRemove.Clear();

                //UnionOf
                foreach (var t in ontologyClassModel.Relations.UnionOf.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyClassModel.Relations.UnionOf.Entries.Remove(c); }
                cacheRemove.Clear();

                //IntersectionOf
                foreach (var t in ontologyClassModel.Relations.IntersectionOf.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyClassModel.Relations.IntersectionOf.Entries.Remove(c); }
                cacheRemove.Clear();

                //OneOf
                foreach (var t in ontologyClassModel.Relations.OneOf.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyClassModel.Relations.OneOf.Entries.Remove(c); }
                cacheRemove.Clear();
            }
        }

        /// <summary>
        /// Clears all the taxonomy entries marked as semantic inferences generated by a reasoner
        /// </summary>
        public static void ClearInferences(this RDFOntologyPropertyModel ontologyPropertyModel) {
            if (ontologyPropertyModel != null) {
                var cacheRemove = new Dictionary<Int64, Object>();

                //SubPropertyOf
                foreach (var t in ontologyPropertyModel.Relations.SubPropertyOf.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyPropertyModel.Relations.SubPropertyOf.Entries.Remove(c); }
                cacheRemove.Clear();

                //EquivalentProperty
                foreach (var t in ontologyPropertyModel.Relations.EquivalentProperty.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyPropertyModel.Relations.EquivalentProperty.Entries.Remove(c); }
                cacheRemove.Clear();

                //InverseOf
                foreach (var t in ontologyPropertyModel.Relations.InverseOf.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyPropertyModel.Relations.InverseOf.Entries.Remove(c); }
                cacheRemove.Clear();
            }
        }

        /// <summary>
        /// Clears all the taxonomy entries marked as semantic inferences generated by a reasoner
        /// </summary>
        public static void ClearInferences(this RDFOntologyData ontologyData) {
            if (ontologyData != null) {
                var cacheRemove = new Dictionary<Int64, Object>();

                //ClassType
                foreach (var t in ontologyData.Relations.ClassType.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyData.Relations.ClassType.Entries.Remove(c); }
                cacheRemove.Clear();

                //SameAs
                foreach (var t in ontologyData.Relations.SameAs.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyData.Relations.SameAs.Entries.Remove(c); }
                cacheRemove.Clear();

                //DifferentFrom
                foreach (var t in ontologyData.Relations.DifferentFrom.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyData.Relations.DifferentFrom.Entries.Remove(c); }
                cacheRemove.Clear();

                //Assertions
                foreach (var t in ontologyData.Relations.Assertions.Where(tEntry => tEntry.InferenceType == RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner)) {
                    cacheRemove.Add(t.TaxonomyEntryID, null);
                }
                foreach (var c in cacheRemove.Keys) { ontologyData.Relations.Assertions.Entries.Remove(c); }
                cacheRemove.Clear();
            }
        }
        #endregion

    }

}